package ClienteP2P;


/**
* ClienteP2P/IServidorCliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServidorCliente.idl
* jueves 6 de abril de 2017 22H29' CEST
*/

public interface IServidorCliente extends IServidorClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IServidorCliente
