package ClienteP2P;


/**
* ClienteP2P/IServidorClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServidorCliente.idl
* viernes 7 de abril de 2017 16H19' CEST
*/

public interface IServidorClienteOperations 
{
  void notificarSolicitudesPendientes (ClienteP2P.Usuario[] solicitudesPendientes);
  void notificarConexion (ClienteP2P.Usuario usuario);
  void notificarDesconexion (ClienteP2P.Usuario usuario);
  void notificarNuevaAmistad (ClienteP2P.Usuario usuario);
} // interface IServidorClienteOperations
