# DO NOT EDIT THIS FILE!
#
# Python module ClienteP2P__POA generated by omniidl

import omniORB
omniORB.updateModule("ClienteP2P__POA")

# ** 1. Stub files contributing to this module
import IServidorCliente_idl

# ** 2. Sub-modules

# ** 3. End
