# Python stubs generated by omniidl from IServidorCliente.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "ClienteP2P"
#
__name__ = "ClienteP2P"
_0_ClienteP2P = omniORB.openModule("ClienteP2P", r"IServidorCliente.idl")
_0_ClienteP2P__POA = omniORB.openModule("ClienteP2P__POA", r"IServidorCliente.idl")


# interface IServidorCliente
_0_ClienteP2P._d_IServidorCliente = (omniORB.tcInternal.tv_objref, "IDL:ClienteP2P/IServidorCliente:1.0", "IServidorCliente")
omniORB.typeMapping["IDL:ClienteP2P/IServidorCliente:1.0"] = _0_ClienteP2P._d_IServidorCliente
_0_ClienteP2P.IServidorCliente = omniORB.newEmptyClass()
class IServidorCliente :
    _NP_RepositoryId = _0_ClienteP2P._d_IServidorCliente[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ClienteP2P.IServidorCliente = IServidorCliente
_0_ClienteP2P._tc_IServidorCliente = omniORB.tcInternal.createTypeCode(_0_ClienteP2P._d_IServidorCliente)
omniORB.registerType(IServidorCliente._NP_RepositoryId, _0_ClienteP2P._d_IServidorCliente, _0_ClienteP2P._tc_IServidorCliente)

# IServidorCliente operations and attributes
IServidorCliente._d_prueba = (((omniORB.tcInternal.tv_string,0), ), None, None)
IServidorCliente._d_shutdown = ((), None, None)

# IServidorCliente object reference
class _objref_IServidorCliente (CORBA.Object):
    _NP_RepositoryId = IServidorCliente._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def prueba(self, *args):
        return _omnipy.invoke(self, "prueba", _0_ClienteP2P.IServidorCliente._d_prueba, args)

    def shutdown(self, *args):
        return _omnipy.invoke(self, "shutdown", _0_ClienteP2P.IServidorCliente._d_shutdown, args)

    __methods__ = ["prueba", "shutdown"] + CORBA.Object.__methods__

omniORB.registerObjref(IServidorCliente._NP_RepositoryId, _objref_IServidorCliente)
_0_ClienteP2P._objref_IServidorCliente = _objref_IServidorCliente
del IServidorCliente, _objref_IServidorCliente

# IServidorCliente skeleton
__name__ = "ClienteP2P__POA"
class IServidorCliente (PortableServer.Servant):
    _NP_RepositoryId = _0_ClienteP2P.IServidorCliente._NP_RepositoryId


    _omni_op_d = {"prueba": _0_ClienteP2P.IServidorCliente._d_prueba, "shutdown": _0_ClienteP2P.IServidorCliente._d_shutdown}

IServidorCliente._omni_skeleton = IServidorCliente
_0_ClienteP2P__POA.IServidorCliente = IServidorCliente
omniORB.registerSkeleton(IServidorCliente._NP_RepositoryId, IServidorCliente)
del IServidorCliente
__name__ = "ClienteP2P"

#
# End of module "ClienteP2P"
#
__name__ = "IServidorCliente_idl"

_exported_modules = ( "ClienteP2P", )

# The end.
