package ClienteP2P;


/**
* ClienteP2P/IClienteServidor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* viernes 14 de abril de 2017 23H17' CEST
*/

public interface IClienteServidor extends IClienteServidorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IClienteServidor
