package ClienteP2P;


/**
* ClienteP2P/IClienteServidorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* sábado, 15 de abril de 2017, 13:20:18 (hora de verano de Europa central)
*/

public interface IClienteServidorOperations 
{
  ClienteP2P.Usuario[] conectarse (String nick, String password, String ip, String puerto, ClienteP2P.IServidorCliente i);
  ClienteP2P.Usuario[] buscarUsuarios (String cadenaBusqueda);
  boolean registrarUsuario (String nick, String password, String ip, String puerto);
  void modificarPassword (String nick, String passwordNueva, String passwordVieja);
  void anhadirAmigo (String nick, String amigo);
  void borrarAmigo (String nick, String amigo);
  void desconectarse (String nick);
  void cambiarIP (String nick, String ipNueva);
  void shutdown ();
} // interface IClienteServidorOperations
