package ClienteP2P;

/**
* ClienteP2P/IClienteServidorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* viernes 14 de abril de 2017 23H17' CEST
*/

public final class IClienteServidorHolder implements org.omg.CORBA.portable.Streamable
{
  public ClienteP2P.IClienteServidor value = null;

  public IClienteServidorHolder ()
  {
  }

  public IClienteServidorHolder (ClienteP2P.IClienteServidor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClienteP2P.IClienteServidorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClienteP2P.IClienteServidorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClienteP2P.IClienteServidorHelper.type ();
  }

}
