package ClienteP2P;


/**
* ClienteP2P/IClienteServidorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* viernes 14 de abril de 2017 23H17' CEST
*/

abstract public class IClienteServidorHelper
{
  private static String  _id = "IDL:ClienteP2P/IClienteServidor:1.0";

  public static void insert (org.omg.CORBA.Any a, ClienteP2P.IClienteServidor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ClienteP2P.IClienteServidor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ClienteP2P.IClienteServidorHelper.id (), "IClienteServidor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ClienteP2P.IClienteServidor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IClienteServidorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ClienteP2P.IClienteServidor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ClienteP2P.IClienteServidor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClienteP2P.IClienteServidor)
      return (ClienteP2P.IClienteServidor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ClienteP2P._IClienteServidorStub stub = new ClienteP2P._IClienteServidorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ClienteP2P.IClienteServidor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClienteP2P.IClienteServidor)
      return (ClienteP2P.IClienteServidor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ClienteP2P._IClienteServidorStub stub = new ClienteP2P._IClienteServidorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
