package ClienteP2P;


/**
* ClienteP2P/IServidorClienteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* sábado, 15 de abril de 2017, 13:20:18 (hora de verano de Europa central)
*/

abstract public class IServidorClienteHelper
{
  private static String  _id = "IDL:ClienteP2P/IServidorCliente:1.0";

  public static void insert (org.omg.CORBA.Any a, ClienteP2P.IServidorCliente that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ClienteP2P.IServidorCliente extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ClienteP2P.IServidorClienteHelper.id (), "IServidorCliente");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ClienteP2P.IServidorCliente read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IServidorClienteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ClienteP2P.IServidorCliente value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ClienteP2P.IServidorCliente narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClienteP2P.IServidorCliente)
      return (ClienteP2P.IServidorCliente)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ClienteP2P._IServidorClienteStub stub = new ClienteP2P._IServidorClienteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ClienteP2P.IServidorCliente unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClienteP2P.IServidorCliente)
      return (ClienteP2P.IServidorCliente)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ClienteP2P._IServidorClienteStub stub = new ClienteP2P._IServidorClienteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
