package ClienteP2P;


/**
* ClienteP2P/IServidorClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* viernes 14 de abril de 2017 23H17' CEST
*/

public interface IServidorClienteOperations 
{
  void hola (String mes);
  void notificarSolicitudesPendientes (ClienteP2P.Usuario[] solicitudesPendientes);
  void notificarConexion (ClienteP2P.Usuario usuario);
  void notificarDesconexion (ClienteP2P.Usuario usuario);
  void notificarNuevaAmistad (ClienteP2P.Usuario usuario);
} // interface IServidorClienteOperations
