package ClienteP2P;


/**
* ClienteP2P/IServidorCliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* sábado, 15 de abril de 2017, 13:20:18 (hora de verano de Europa central)
*/

public interface IServidorCliente extends IServidorClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IServidorCliente
