package ClienteP2P;


/**
* ClienteP2P/IServidorClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* sábado, 15 de abril de 2017, 13:20:18 (hora de verano de Europa central)
*/

public interface IServidorClienteOperations 
{
  void hola (String mes);
  void notificarSolicitudesPendientes (ClienteP2P.Usuario[] solicitudesPendientes);
  void notificarConexion (ClienteP2P.Usuario usuario);
  void notificarDesconexion (ClienteP2P.Usuario usuario);
  void notificarNuevaAmistad (ClienteP2P.Usuario usuario);
} // interface IServidorClienteOperations
