package ClienteP2P;


/**
* ClienteP2P/listaUsuariosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* viernes 14 de abril de 2017 23H17' CEST
*/

abstract public class listaUsuariosHelper
{
  private static String  _id = "IDL:ClienteP2P/listaUsuarios:1.0";

  public static void insert (org.omg.CORBA.Any a, ClienteP2P.Usuario[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ClienteP2P.Usuario[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ClienteP2P.UsuarioHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ClienteP2P.listaUsuariosHelper.id (), "listaUsuarios", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ClienteP2P.Usuario[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ClienteP2P.Usuario value[] = null;
    int _len0 = istream.read_long ();
    value = new ClienteP2P.Usuario[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ClienteP2P.UsuarioHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ClienteP2P.Usuario[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ClienteP2P.UsuarioHelper.write (ostream, value[_i0]);
  }

}
