module ClienteP2P
{
    struct Usuario {
        string nick;
        string ip;
        string puerto;
        boolean conectado;
    };
    typedef sequence<Usuario> listaUsuarios;
    interface IServidorCliente {
        oneway void notificarSolicitudesPendientes(in listaUsuarios solicitudesPendientes);
        oneway void notificarConexion(in Usuario usuario);
        oneway void notificarDesconexion(in Usuario usuario);
        oneway void notificarNuevaAmistad(in Usuario usuario);
        oneway void prueba(in string str);
        oneway void shutdown();
    };
};